<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Structural.Desktop.Core.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Structural.Desktop.Core\Structural.Desktop.Core.csproj" />
  </ItemGroup>
</Project>
