[package]
name = "structural-assurance"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
structural-audit = { path = "../audit" }
structural-key-management = { path = "../key-management" }
uuid.workspace = true
